ww_homepage:
    pattern: /
    defaults: { _controller: "PumWoodworkBundle:Homepage:homepage" }


ww_project_definition_list:
    pattern: /projects
    defaults: { _controller: "PumWoodworkBundle:Project:list" }


ww_beam_definition_list:
    pattern: /beams
    defaults: { _controller: "PumWoodworkBundle:Beam:list" }


ww_object_definition_list:
    pattern: /objects/{beamName}
    defaults: { _controller: "PumWoodworkBundle:ObjectDefinition:list" }

ww_object_definition_view:
    pattern: /objects/{beamName}/{name}/view
    defaults: { _controller: "PumWoodworkBundle:ObjectDefinition:view" }

ww_object_definition_edit:
    pattern: /objects/{beamName}/{name}/edit
    defaults: { _controller: "PumWoodworkBundle:ObjectDefinition:edit" }

ww_object_definition_delete:
    pattern: /objects/{beamName}/{name}/delete
    defaults: { _controller: "PumWoodworkBundle:ObjectDefinition:delete" }

ww_object_definition_create:
    pattern: /objects/{beamName}/create
    defaults: { _controller: "PumWoodworkBundle:ObjectDefinition:create" }
