ww_homepage:
    pattern: /
    defaults: { _controller: "PumWoodworkBundle:Homepage:homepage" }


ww_project_definition_list:
    pattern: /projects
    defaults: { _controller: "PumWoodworkBundle:Project:list" }


ww_beam_definition_list:
    pattern: /beams
    defaults: { _controller: "PumWoodworkBundle:Beam:list" }

ww_beam_definition_create:
    pattern: /beams/create
    defaults: { _controller: "PumWoodworkBundle:Beam:create" }


ww_object_definition_list:
    pattern: /objects/{beamName}
    defaults: { _controller: "PumWoodworkBundle:ObjectDefinition:list" }

ww_object_definition_create:
    pattern: /objects/{beamName}/create
    defaults: { _controller: "PumWoodworkBundle:ObjectDefinition:create" }

ww_object_definition_view:
    pattern: /objects/{beamName}/{name}/view
    defaults: { _controller: "PumWoodworkBundle:ObjectDefinition:view" }

ww_object_definition_edit:
    pattern: /objects/{beamName}/{name}/edit
    defaults: { _controller: "PumWoodworkBundle:ObjectDefinition:edit" }

ww_object_definition_delete:
    pattern: /objects/{beamName}/{name}/delete
    defaults: { _controller: "PumWoodworkBundle:ObjectDefinition:delete" }

# Field types
ww_ajax_field_type_options:
    pattern: /admin/ajax/field-type
    defaults: { _controller: "PumWoodworkBundle:Ajax:fieldTypeOptions" }

# Schema
ww_schema:
    pattern: /schema
    defaults: { _controller: "PumWoodworkBundle:Schema:index" }

# Schema
ww_schema_update:
    pattern: /schema/update
    defaults: { _controller: "PumWoodworkBundle:Schema:update" }
