Pum\Core\Definition\Beam:
    type: entity
    table: schema_beam
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        seed:
          type: string
          length: 32
        name:
            type: string
            length: 100
            unique: true
        alias:
            type: string
            length: 100
            nullable: true
        icon:
            type: string
            length: 32
        color:
            type: string
            length: 32
    oneToMany:
        objects:
            targetEntity: ObjectDefinition
            mappedBy: beam
            orphanRemoval: true
            cascade: [ persist, remove ]
            fetch: EXTRA_LAZY
    manyToMany:
        projects:
            targetEntity: Project
            mappedBy:   beams
            cascade: [ persist, remove ]
            orphanRemoval: true
            fetch: EXTRA_LAZY
