Pum\Core\Definition\Beam:
    type: entity
    table: schema_beam
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
    oneToMany:
        objects:
            targetEntity: ObjectDefinition
            mappedBy: beam
            cascade: [ persist, remove ]
            fetch: EXTRA_LAZY
