Pum\Core\Definition\FieldDefinition:
    type: entity
    table: schema_object_field
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        type:
            type: string
            length: 100
        typeOptions:
            type: json_array
    manyToOne:
        object:
            targetEntity: ObjectDefinition
            inversedBy: fields
            joinColumn:
                name: schema_object_id
                referencedColumnName: id
                onDelete: CASCADE
    uniqueConstraints:
        object_name_index:
            columns: schema_object_id, name
