Pum\Core\Definition\ObjectView:
    type: entity
    table: schema_object_object_view
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        private:
            column: is_private # private is a reserved keyword
            type: boolean
        columns:
            type: json_array
    manyToOne:
        objectDefinition:
            targetEntity: ObjectDefinition
            inversedBy: objectViews
            onDelete: CASCADE
            joinColumn:
                name: schema_object_id
                referencedColumnName: id
    uniqueConstraints:
        table_view_name_index:
            columns: schema_object_id, name
