Pum\Core\Definition\ObjectDefinition:
    type: entity
    table: schema_object
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        classname:
            type: string
            length: 100
            nullable: true
    oneToMany:
        fields:
            targetEntity: FieldDefinition
            mappedBy: object
            indexBy: name
            orphanRemoval: true
            cascade: [ persist, remove ]
            fetch: EXTRA_LAZY
    manyToOne:
        beam:
            targetEntity: Beam
            inversedBy:   objects
            joinColumn:
                name: schema_beam_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
