Pum\Core\Definition\SearchField:
    type: entity
    table: schema_object_search_field
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 64
        expression:
            type: string
            length: 255
        weight:
            type: integer
            length: 10
        type:
            type: string
            length: 20
    manyToOne:
        objectDefinition:
            targetEntity: Pum\Core\Definition\ObjectDefinition
            inversedBy: searchFields
            onDelete: CASCADE
            joinColumn:
                name: schema_object_id
                referencedColumnName: id
