Pum\Core\Definition\View\TableView:
    type: entity
    table: schema_object_table_view
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        private:
            column: is_private # private is a reserved keyword
            type: boolean
        filters:
            type: json_array
        defaultSortOrder:
            type: string
            length: 10
    manyToOne:
        objectDefinition:
            targetEntity: Pum\Core\Definition\ObjectDefinition
            inversedBy: tableViews
            onDelete: CASCADE
            joinColumn:
                name: schema_object_id
                referencedColumnName: id
    oneToMany:
        columns:
            targetEntity: TableViewField
            mappedBy: tableview
            orphanRemoval: true
            cascade: [ persist, remove ]
            fetch: EXTRA_LAZY
    oneToOne:
        defaultSortColumn:
            targetEntity: TableViewField
            joinColumn:
                name: schema_object_table_view_field_id
                referencedColumnName: id
    uniqueConstraints:
        table_view_name_index:
            columns: schema_object_id, name
