Pum\Core\Definition\View\TableViewFilter:
    type: entity
    table: schema_object_table_view_filter
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        values:
            type: json_array
    manyToOne:
        tableview:
            targetEntity: TableView
            inversedBy: filters
            joinColumn:
                name: schema_object_table_view_id
                referencedColumnName: id
                onDelete: CASCADE
        column:
            targetEntity: TableViewField
            joinColumn:
                name: schema_object_table_view_field_id
                referencedColumnName: id
                onDelete: CASCADE
