Pum\Core\Definition\View\FormView:
    type: entity
    table: schema_object_form_view
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        private:
            column: is_private # private is a reserved keyword
            type: boolean
        default:
            column: is_default # default is a reserved keyword
            type: boolean
        type:
            type: smallint
            nullable: true
    oneToOne:
        view:
            targetEntity: Pum\Core\Definition\View\FormViewNode
            cascade: [ persist, remove ]
            joinColumn:
                name:  schema_object_form_view_node_id
                referencedColumnName: id
                onDelete: SET NULL
    manyToOne:
        objectDefinition:
            targetEntity: Pum\Core\Definition\ObjectDefinition
            inversedBy: formViews
            onDelete: CASCADE
            joinColumn:
                name: schema_object_id
                referencedColumnName: id
    oneToMany:
        fields:
            orderBy: { 'sequence': 'asc' }
            targetEntity: Pum\Core\Definition\View\FormViewField
            mappedBy: formView
            orphanRemoval: true
            cascade: [ persist, remove ]
    uniqueConstraints:
        form_view_name_index:
            columns: schema_object_id, name
    lifecycleCallbacks:
        postLoad: [ onPostLoad ]
