Pum\Core\Definition\View\ObjectView:
    type: entity
    table: schema_object_object_view
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        private:
            column: is_private # private is a reserved keyword
            type: boolean
    manyToOne:
        objectDefinition:
            targetEntity: Pum\Core\Definition\ObjectDefinition
            inversedBy: objectViews
            onDelete: CASCADE
            joinColumn:
                name: schema_object_id
                referencedColumnName: id
    oneToMany:
        fields:
            orderBy: { 'sequence': 'asc' }
            targetEntity: ObjectViewField
            mappedBy: objectView
            orphanRemoval: true
            cascade: [ persist, remove ]
    uniqueConstraints:
        object_view_name_index:
            columns: schema_object_id, name
