Pum\Core\Definition\View\FormViewField:
    type: entity
    table: schema_object_form_view_field
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            length: 100
        view:
            type: string
            length: 100
        sequence:
            type: integer
        placeholder:
            type: string
            length: 100
            nullable: true
        help:
            type: string
            nullable: true
        options:
            type: array
    manyToOne:
        formView:
            targetEntity: FormView
            inversedBy: fields
            joinColumn:
                name: schema_object_form_view_id
                referencedColumnName: id
                onDelete: CASCADE
        field:
            targetEntity: Pum\Core\Definition\FieldDefinition
            joinColumn:
                name:  schema_object_field_id
                referencedColumnName: id
                onDelete: CASCADE
    uniqueConstraints:
        form_view_field_label_index:
            columns: schema_object_form_view_id, label
