Pum\Core\Definition\View\FormView:
    type: entity
    table: schema_object_form_view
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        private:
            column: is_private # private is a reserved keyword
            type: boolean
    manyToOne:
        objectDefinition:
            targetEntity: Pum\Core\Definition\ObjectDefinition
            inversedBy: formViews
            onDelete: CASCADE
            joinColumn:
                name: schema_object_id
                referencedColumnName: id
    oneToMany:
        fields:
            targetEntity: Pum\Core\Definition\View\FormViewField
            mappedBy: formView
    uniqueConstraints:
        form_view_name_index:
            columns: schema_object_id, name
