Pum\Core\Definition\View\TableViewFilter:
    type: entity
    table: schema_object_table_view_filter
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 10
        value:
            type: string
            length: 100
    manyToOne:
        tableview:
            targetEntity: TableView
            inversedBy: filters
            joinColumn:
                name: schema_object_table_view_id
                referencedColumnName: id
                onDelete: CASCADE
        column:
            targetEntity: TableViewField
            joinColumn:
                name: schema_object_table_view_field_id
                referencedColumnName: id
                onDelete: CASCADE
