Pum\Core\Definition\View\TableView:
    type: entity
    table: schema_object_table_view
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        private:
            column: is_private # private is a reserved keyword
            type: boolean
    oneToOne:
        defaultSort:
            targetEntity: TableViewSort
            orphanRemoval: false
            cascade: [ persist, detach ]
            joinColumn:
                name: schema_object_table_view_sort_id
                referencedColumnName: id
                onDelete: SET NULL
    oneToMany:
        columns:
            orderBy: { 'sequence': 'asc' }
            targetEntity: TableViewField
            mappedBy: tableview
            orphanRemoval: true
            cascade: [ persist, remove ]
            fetch: EXTRA_LAZY
    manyToOne:
        objectDefinition:
            targetEntity: Pum\Core\Definition\ObjectDefinition
            inversedBy: tableViews
            joinColumn:
                name: schema_object_id
                referencedColumnName: id
                onDelete: CASCADE
    uniqueConstraints:
        table_view_name_index:
            columns: schema_object_id, name
