Pum\Core\Definition\FieldDefinition:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name, object ]
    properties:
        name:
            - NotBlank: ~
        type:
            - NotBlank: ~

Pum\Core\Definition\Project:
    properties:
        name:
            - NotBlank: ~
        beams:
            - Pum\Bundle\CoreBundle\Validator\Constraints\NoBeamTwice: ~

Pum\Core\Definition\Beam:
    properties:
        name:
            - NotBlank: ~

Pum\Core\Definition\ObjectDefinition:
    properties:
        fields:
            - Valid: ~
