Pum\Core\Definition\FieldDefinition:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name, object ]
    properties:
        name:
            - NotBlank: ~
            - Pum\Bundle\CoreBundle\Validator\Constraints\FieldName: ~
            - Pum\Bundle\CoreBundle\Validator\Constraints\SqlReservedKeywords: ~
        type:
            - NotBlank: ~

Pum\Core\Definition\Project:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name ]
    properties:
        name:
            - NotBlank: ~
        beams:
            - Pum\Bundle\CoreBundle\Validator\Constraints\NoBeamTwice: ~

Pum\Core\Definition\Beam:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name ]
    properties:
        name:
            - NotBlank: ~
        color:
            - NotBlank: ~
        icon:
            - NotBlank: ~

Pum\Core\Definition\Relation:
    properties:
        from:
            - NotBlank: ~
        fromName:
            - NotBlank: ~
        to:
            - NotBlank: ~

Pum\Core\Definition\ObjectDefinition:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name, beam ]
    properties:
        name:
            - NotBlank: ~
        fields:
            - Valid: ~

Pum\Core\Definition\TableView:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name, objectDefinition ]
    properties:
        name:
            - NotBlank: ~
