Pum\Core\Definition\FieldDefinition:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name, object ]
    properties:
        name:
            - NotBlank: ~
            - Pum\Bundle\CoreBundle\Validator\Constraints\FieldName: ~
            - Pum\Bundle\CoreBundle\Validator\Constraints\SqlReservedKeywords: ~
        type:
            - NotBlank: ~

Pum\Core\Definition\Project:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name ]
    properties:
        name:
            - NotBlank: ~
        beams:
            - Pum\Bundle\CoreBundle\Validator\Constraints\NoBeamTwice: ~

Pum\Core\Definition\Beam:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: [ name ], groups: [ Default, Import ] }
    properties:
        name:
            - NotBlank: { groups: [ Default, Import ] }
        color:
            - NotBlank: ~
        icon:
            - NotBlank: ~

Pum\Core\Definition\ObjectDefinition:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name, beam ]
    properties:
        name:
            - NotBlank: ~
        fields:
            - Valid: ~

Pum\Core\Definition\View\TableView:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name, objectDefinition ]
    properties:
        name:
            - NotBlank: ~
        columns:
            - Valid: ~

Pum\Core\Definition\View\TableViewField:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ label, tableview ]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ sequence, tableview ]
    properties:
        label:
            - NotBlank: ~
        sequence:
            - NotBlank: ~

Pum\Core\Definition\View\ObjectView:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name, objectDefinition ]
    properties:
        name:
            - NotBlank: ~
        fields:
            - Valid: ~

Pum\Core\Definition\View\ObjectViewField:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ label, objectView ]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ sequence, objectView ]
    properties:
        label:
            - NotBlank: ~
        sequence:
            - NotBlank: ~

Pum\Core\Definition\View\FormView:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name, objectDefinition ]
    properties:
        name:
            - NotBlank: ~
        fields:
            - Valid: ~

Pum\Core\Definition\View\FormViewField:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ label, formView ]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ sequence, formView ]
    properties:
        label:
            - NotBlank: ~
        sequence:
            - NotBlank: ~
