Pum\Bundle\AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ username ]
    properties:
        username:
            - NotBlank: ~
        fullname:
            - NotBlank: ~
        # raw password is not persisted, so it's not possible to validate password
