Pum\Bundle\AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ username ]
    properties:
        username:
            - NotBlank: ~
        fullname:
            - NotBlank: ~
        # raw password is not persisted, so it's not possible to validate password
Pum\Bundle\AppBundle\Entity\GroupPermission:
    properties:
        group:
            - NotNull: ~
        attribute:
            - NotNull: ~
Pum\Bundle\AppBundle\Entity\UserPermission:
    properties:
        user:
            - NotNull: ~
        attribute:
            - NotNull: ~
